<a href="https://colab.research.google.com/github/SonyZaman/Python/blob/main/19_Pandas_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Table of Contents

1.  [Introduction](#introduction)
2.  [Importing Libraries](#importing-libraries)
3.  [Creating DataFrames](#creating-dataframes)
    *   [From Lists](#from-lists)
    *   [From Dictionaries](#from-dictionaries)
    *   [From CSV Files](#from-csv-files)
4.  [DataFrame Attributes](#dataframe-attributes)
    *   [`shape`](#shape)
    *   [`dtypes`](#dtypes)
    *   [`index`](#index)
    *   [`columns`](#columns)
    *   [`values`](#values)
5.  [DataFrame Inspection Methods](#dataframe-inspection-methods)
    *   [`head()`](#head)
    *   [`tail()`](#tail)
    *   [`sample()`](#sample)
    *   [`info()`](#info)
    *   [`describe()`](#describe)
    *   [`isnull()`](#isnull)
    *   [`duplicated()`](#duplicated)
6.  [Data Manipulation](#data-manipulation)
    *   [`rename()`](#rename)
    *   [`set_index()`](#set_index)
    *   [`sum()`](#sum)
    *   [`mean()`](#mean)
    *   [`median()`](#median)
    *   [`var()`](#var)
    *   [`std()`](#std)
    *   [`max()`](#max)
    *   [`min()`](#min)
    *   [`astype()`](#astype)
    *   [`dropna()`](#dropna)
    *   [`value_counts()`](#value_counts)
    *   [`pd.concat()`](#pdconcat)
    *   [`sort_values()`](#sort_values)
7.  [Data Selection](#data-selection)
    *   [Selecting Columns](#selecting-columns)
    *   [Selecting Rows (iloc)](#selecting-rows-iloc)
    *   [Selecting Rows (loc)](#selecting-rows-loc)
    *   [Selecting Rows and Columns](#selecting-rows-and-columns)
8.  [Data Filtering](#data-filtering)
    *   [Boolean Filtering](#boolean-filtering)
    *   [`str.contains()`](#strcontains)
    *   [`str.split().apply()`](#strsplitapply)
9.  [Adding New Columns](#adding-new-columns)

### Importing Libraries

In [479]:
import numpy as np
import pandas as pd

### Creating DataFrame

In [480]:
# using lists
student_data = [
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
]

pd.DataFrame(student_data,columns=['iq','marks','package'])

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [481]:
# using dicts

student_dict = {
    'name':['Sony','Labib','Hasan','Rahman','Zaman','Karim'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

students = pd.DataFrame(student_dict)
students.set_index('name',inplace=True)
students

         iq  marks  package
name
Sony    100     80       10
Labib    90     70        7
Hasan   120    100       14
Rahman   80     50        2
Zaman     0      0        0
Karim     0      0        0

In [482]:
# using read_csv
movies = pd.read_csv('movies.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Gladiator,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Russell Crowe,4 wins,11 January 2019 (USA)
1,Inception,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Leonardo DiCaprio,NaN,11 January 2019 (India)
2,Inception,tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Leonardo DiCaprio,NaN,11 January 2019 (USA)
3,Titanic,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Kate Winslet,NaN,18 January 2019 (USA)
4,Forrest Gump,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Tom Hanks,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Avengers: Endgame,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Robert Downey Jr.,NaN,7 November 2001 (India)
1625,Titanic,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Kate Winslet,NaN,16 November 2001 (India)
1626,Fight Club,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Brad Pitt,NaN,NaN
1627,Oppenheimer,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Cillian Murphy,NaN,1 November 2019 (USA)
1628,Titanic,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Kate Winslet,NaN,TV Series (2011–2012)

In [483]:
cricket = pd.read_csv('cricket_matches.csv')
cricket

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1304113,Melbourne,2022-05-19,2022,67,Pakistan,West Indies,Eden Gardens,Pakistan,bat,N,Pakistan,Wickets,8.0,NaN,Mohammad Rizwan,"Babar Azam, Shaheen Afridi, Mohammad Rizwan","Kane Williamson, Trent Boult, Devon Conway",Richard Kettleborough,Chris Gaffaney
1,1304107,Melbourne,2022-05-14,2022,61,Bangladesh,Pakistan,Sher-e-Bangla National Stadium,Bangladesh,bat,N,Bangladesh,Runs,54.0,NaN,Shakib Al Hasan,"Babar Azam, Shaheen Afridi, Mohammad Rizwan","Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman",Aleem Dar,Paul Reiffel
2,1304090,Mumbai,2022-04-30,2022,44,West Indies,Pakistan,Narendra Modi Stadium,West Indies,field,N,West Indies,Wickets,5.0,NaN,Jason Holder,"Rashid Khan, Rahmanullah Gurbaz, Mohammad Nabi","Nicholas Pooran, Jason Holder, Shimron Hetmyer",Rod Tucker,Nitin Menon
3,1304078,Manchester,2022-04-20,2022,32,Pakistan,Sri Lanka,Wankhede Stadium,Pakistan,field,N,Pakistan,Wickets,9.0,NaN,Shaheen Afridi,"Quinton de Kock, Kagiso Rabada, Aiden Markram","Babar Azam, Shaheen Afridi, Mohammad Rizwan",Chris Gaffaney,Richard Kettleborough
4,1304075,Ahmedabad,2022-04-17,2022,29,New Zealand,Sri Lanka,Melbourne Cricket Ground,Sri Lanka,field,N,Sri Lanka,Wickets,3.0,NaN,Pathum Nissanka,"Quinton de Kock, Kagiso Rabada, Aiden Markram","Wanindu Hasaranga, Kusal Mendis, Pathum Nissanka",Chris Gaffaney,Richard Kettleborough
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,336031,Kolkata,2008-05-23,2007/08,48,England,New Zealand,Adelaide Oval,England,field,N,New Zealand,Wickets,6.0,NaN,Trent Boult,"Kane Williamson, Trent Boult, Devon Conway","Joe Root, Ben Stokes, Jos Buttler",Chris Gaffaney,Nitin Menon
114,336024,Sydney,2008-05-18,2007/08,42,Australia,South Africa,Adelaide Oval,Australia,field,N,Australia,Runs,25.0,NaN,Steve Smith,"Pat Cummins, Steve Smith, David Warner","Babar Azam, Shaheen Afridi, Mohammad Rizwan",Aleem Dar,Nitin Menon
115,336009,Kolkata,2008-05-08,2007/08,28,New Zealand,Bangladesh,Old Trafford Cricket Ground,Bangladesh,field,N,New Zealand,Wickets,4.0,NaN,Devon Conway,"Kane Williamson, Trent Boult, Devon Conway","Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman",Nitin Menon,Richard Kettleborough
116,336007,Adelaide,2008-05-06,2007/08,26,Australia,Pakistan,Eden Gardens,Australia,field,N,Australia,Wickets,7.0,NaN,Steve Smith,"Pat Cummins, Steve Smith, David Warner","Babar Azam, Shaheen Afridi, Mohammad Rizwan",Richard Kettleborough,Paul Reiffel
117,336034,Kolkata,2008-05-03,2007/08,21,New Zealand,Bangladesh,Eden Gardens,Bangladesh,field,N,Bangladesh,Runs,3.0,NaN,Mustafizur Rahman,"Pat Cummins, Steve Smith, David Warner","Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman",Paul Reiffel,Richard Kettleborough

### DataFrame Attributes and Methods

In [484]:
# shape
print(movies.shape)
print(cricket.shape)

(1629, 18)
(118, 20)

In [485]:
# dtypes
cricket.dtypes

ID                   int64
City                object
Date                object
Season              object
MatchNumber         object
Team1               object
Team2               object
Venue               object
TossWinner          object
TossDecision        object
SuperOver           object
WinningTeam         object
WonBy               object
Margin             float64
method              object
Player_of_Match     object
Team1Players        object
Team2Players        object
Umpire1             object
Umpire2             object
dtype: object

In [486]:
# index
print(movies.index)
print(cricket.index)

RangeIndex(start=0, stop=1629, step=1)
RangeIndex(start=0, stop=118, step=1)

In [487]:
# columns
print(movies.columns,end='\n\n')
print(cricket.columns,end='\n\n')
print(students.columns,end='\n\n')

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

Index(['iq', 'marks', 'package'], dtype='object')

In [488]:
# values (DataFrame to 2D NumPy a)
cricket.values

array([[1304113, 'Melbourne', '2022-05-19', ...,
        'Kane Williamson, Trent Boult, Devon Conway',
        'Richard Kettleborough', 'Chris Gaffaney'],
       [1304107, 'Melbourne', '2022-05-14', ...,
        'Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman', 'Aleem Dar',
        'Paul Reiffel'],
       [1304090, 'Mumbai', '2022-04-30', ...,
        'Nicholas Pooran, Jason Holder, Shimron Hetmyer', 'Rod Tucker',
        'Nitin Menon'],
       ...,
       [336009, 'Kolkata', '2008-05-08', ...,
        'Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman', 'Nitin Menon',
        'Richard Kettleborough'],
       [336007, 'Adelaide', '2008-05-06', ...,
        'Babar Azam, Shaheen Afridi, Mohammad Rizwan',
        'Richard Kettleborough', 'Paul Reiffel'],
       [336034, 'Kolkata', '2008-05-03', ...,
        'Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman',
        'Paul Reiffel', 'Richard Kettleborough']], dtype=object)

In [489]:
# head(first n values)
cricket.head(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1304113,Melbourne,2022-05-19,2022,67,Pakistan,West Indies,Eden Gardens,Pakistan,bat,N,Pakistan,Wickets,8.0,NaN,Mohammad Rizwan,"Babar Azam, Shaheen Afridi, Mohammad Rizwan","Kane Williamson, Trent Boult, Devon Conway",Richard Kettleborough,Chris Gaffaney
1,1304107,Melbourne,2022-05-14,2022,61,Bangladesh,Pakistan,Sher-e-Bangla National Stadium,Bangladesh,bat,N,Bangladesh,Runs,54.0,NaN,Shakib Al Hasan,"Babar Azam, Shaheen Afridi, Mohammad Rizwan","Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman",Aleem Dar,Paul Reiffel
2,1304090,Mumbai,2022-04-30,2022,44,West Indies,Pakistan,Narendra Modi Stadium,West Indies,field,N,West Indies,Wickets,5.0,NaN,Jason Holder,"Rashid Khan, Rahmanullah Gurbaz, Mohammad Nabi","Nicholas Pooran, Jason Holder, Shimron Hetmyer",Rod Tucker,Nitin Menon
3,1304078,Manchester,2022-04-20,2022,32,Pakistan,Sri Lanka,Wankhede Stadium,Pakistan,field,N,Pakistan,Wickets,9.0,NaN,Shaheen Afridi,"Quinton de Kock, Kagiso Rabada, Aiden Markram","Babar Azam, Shaheen Afridi, Mohammad Rizwan",Chris Gaffaney,Richard Kettleborough
4,1304075,Ahmedabad,2022-04-17,2022,29,New Zealand,Sri Lanka,Melbourne Cricket Ground,Sri Lanka,field,N,Sri Lanka,Wickets,3.0,NaN,Pathum Nissanka,"Quinton de Kock, Kagiso Rabada, Aiden Markram","Wanindu Hasaranga, Kusal Mendis, Pathum Nissanka",Chris Gaffaney,Richard Kettleborough

In [490]:
# tail(last n values)
cricket.tail(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
113,336031,Kolkata,2008-05-23,2007/08,48,England,New Zealand,Adelaide Oval,England,field,N,New Zealand,Wickets,6.0,NaN,Trent Boult,"Kane Williamson, Trent Boult, Devon Conway","Joe Root, Ben Stokes, Jos Buttler",Chris Gaffaney,Nitin Menon
114,336024,Sydney,2008-05-18,2007/08,42,Australia,South Africa,Adelaide Oval,Australia,field,N,Australia,Runs,25.0,NaN,Steve Smith,"Pat Cummins, Steve Smith, David Warner","Babar Azam, Shaheen Afridi, Mohammad Rizwan",Aleem Dar,Nitin Menon
115,336009,Kolkata,2008-05-08,2007/08,28,New Zealand,Bangladesh,Old Trafford Cricket Ground,Bangladesh,field,N,New Zealand,Wickets,4.0,NaN,Devon Conway,"Kane Williamson, Trent Boult, Devon Conway","Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman",Nitin Menon,Richard Kettleborough
116,336007,Adelaide,2008-05-06,2007/08,26,Australia,Pakistan,Eden Gardens,Australia,field,N,Australia,Wickets,7.0,NaN,Steve Smith,"Pat Cummins, Steve Smith, David Warner","Babar Azam, Shaheen Afridi, Mohammad Rizwan",Richard Kettleborough,Paul Reiffel
117,336034,Kolkata,2008-05-03,2007/08,21,New Zealand,Bangladesh,Eden Gardens,Bangladesh,field,N,Bangladesh,Runs,3.0,NaN,Mustafizur Rahman,"Pat Cummins, Steve Smith, David Warner","Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman",Paul Reiffel,Richard Kettleborough

In [491]:
# sample(random n values)
cricket.sample(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
36,1136596,Kolkata,2018-05-05,2018,36,Australia,South Africa,Wankhede Stadium,Australia,bat,N,Australia,Wickets,7.0,NaN,David Warner,"Virat Kohli, Rohit Sharma, Jasprit Bumrah","Pat Cummins, Steve Smith, David Warner",Aleem Dar,Chris Gaffaney
11,1254087,Mumbai,2021-09-20,2021,31,Afghanistan,West Indies,Wankhede Stadium,Afghanistan,bat,N,Afghanistan,Wickets,9.0,NaN,Mohammad Nabi,"Rashid Khan, Rahmanullah Gurbaz, Mohammad Nabi","Virat Kohli, Rohit Sharma, Jasprit Bumrah",Richard Kettleborough,Chris Gaffaney
83,548324,Manchester,2012-04-15,2012,18,New Zealand,Afghanistan,Old Trafford Cricket Ground,Afghanistan,bat,N,Afghanistan,Runs,59.0,NaN,Rashid Khan,"Rashid Khan, Rahmanullah Gurbaz, Mohammad Nabi","Pat Cummins, Steve Smith, David Warner",Marais Erasmus,Nitin Menon
95,501202,Manchester,2011-04-10,2011,5,England,New Zealand,Lord's Cricket Ground,New Zealand,bat,N,New Zealand,Wickets,7.0,NaN,Kane Williamson,"Kane Williamson, Trent Boult, Devon Conway","Wanindu Hasaranga, Kusal Mendis, Pathum Nissanka",Kumar Dharmasena,Richard Kettleborough
15,1254071,Sydney,2021-04-21,2021,14,Australia,India,Narendra Modi Stadium,Australia,bat,N,Australia,Wickets,9.0,NaN,David Warner,"Rashid Khan, Rahmanullah Gurbaz, Mohammad Nabi","Pat Cummins, Steve Smith, David Warner",Marais Erasmus,Nitin Menon

In [492]:
# info
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1629 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [493]:
# info (Non-Null count,Dtype)
cricket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               118 non-null    int64
 1   City             118 non-null    object
 2   Date             118 non-null    object
 3   Season           118 non-null    object
 4   MatchNumber      118 non-null    object
 5   Team1            118 non-null    object
 6   Team2            118 non-null    object
 7   Venue            118 non-null    object
 8   TossWinner       118 non-null    object
 9   TossDecision     118 non-null    object
 10  SuperOver        117 non-null    object
 11  WinningTeam      118 non-null    object
 12  WonBy            118 non-null    object
 13  Margin           116 non-null    float64
 14  method           3 non-null      object
 15  Player_of_Match  118 non-null    object
 16  Team1Players     118 non-null    object
 17  Team2Players     118 non-null    object
 18  Umpire1          118 non-null    object
 19  Umpire2          118 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 18.6+ KB

In [494]:
# describe (statistics)
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [495]:
cricket.describe()

                 ID      Margin
count  1.180000e+02  116.000000
mean   8.296074e+05   19.491379
std    3.444116e+05   26.069971
min    3.360070e+05    2.000000
25%    5.012538e+05    6.000000
50%    8.297920e+05    8.000000
75%    1.175370e+06   22.000000
max    1.304113e+06  138.000000

In [496]:
# isnull
movies.isnull()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1625,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1626,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True
1627,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1628,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

In [497]:
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 0
wins_nominations     922
release_date         107
dtype: int64

In [498]:
# duplicate
print(students)
students.duplicated()

         iq  marks  package
name
Sony    100     80       10
Labib    90     70        7
Hasan   120    100       14
Rahman   80     50        2
Zaman     0      0        0
Karim     0      0        0

name
Sony      False
Labib     False
Hasan     False
Rahman    False
Zaman     False
Karim      True
dtype: bool

In [499]:
students.duplicated().sum()

np.int64(1)

In [500]:
# rename
students

         iq  marks  package
name
Sony    100     80       10
Labib    90     70        7
Hasan   120    100       14
Rahman   80     50        2
Zaman     0      0        0
Karim     0      0        0

In [501]:
students.rename(columns={'marks':'percent','package':'lpa'},inplace=True)

In [502]:
students

         iq  percent  lpa
name
Sony    100       80   10
Labib    90       70    7
Hasan   120      100   14
Rahman   80       50    2
Zaman     0        0    0
Karim     0        0    0

### Math Methods

In [503]:
students

         iq  percent  lpa
name
Sony    100       80   10
Labib    90       70    7
Hasan   120      100   14
Rahman   80       50    2
Zaman     0        0    0
Karim     0        0    0

In [504]:
# sum(by default column wise)
students.sum()

iq         390
percent    300
lpa         33
dtype: int64

In [505]:
# column wise
students.sum(axis=0)

iq         390
percent    300
lpa         33
dtype: int64

In [506]:
# row wise
students.sum(axis=1)

name
Sony      190
Labib     167
Hasan     234
Rahman    132
Zaman       0
Karim       0
dtype: int64

In [507]:
# col wise
students.mean(axis=0)

iq         65.0
percent    50.0
lpa         5.5
dtype: float64

In [508]:
# row wise
students.mean(axis=1)

name
Sony      63.333333
Labib     55.666667
Hasan     78.000000
Rahman    44.000000
Zaman      0.000000
Karim      0.000000
dtype: float64

In [509]:
students.median()

iq         85.0
percent    60.0
lpa         4.5
dtype: float64

In [510]:
students.var()

iq         2710.0
percent    1760.0
lpa          33.5
dtype: float64

In [511]:
students.std()

iq         52.057660
percent    41.952354
lpa         5.787918
dtype: float64

In [512]:
students.max()

iq         120
percent    100
lpa         14
dtype: int64

In [513]:
students.min()

iq         0
percent    0
lpa        0
dtype: int64

### Selecting cols from a DataFrame

In [514]:
# single cols
movies['title_x']

0               Gladiator
1               Inception
2               Inception
3                 Titanic
4            Forrest Gump
              ...
1624    Avengers: Endgame
1625              Titanic
1626           Fight Club
1627          Oppenheimer
1628              Titanic
Name: title_x, Length: 1629, dtype: object

In [515]:
cricket['Venue']

0                        Eden Gardens
1      Sher-e-Bangla National Stadium
2               Narendra Modi Stadium
3                    Wankhede Stadium
4            Melbourne Cricket Ground
                    ...
113                     Adelaide Oval
114                     Adelaide Oval
115       Old Trafford Cricket Ground
116                      Eden Gardens
117                      Eden Gardens
Name: Venue, Length: 118, dtype: object

In [516]:
type(cricket['Venue'])

pandas.core.series.Series

In [517]:
# multiple cols
movies[['year_of_release','actors','title_x']]

      year_of_release             actors            title_x
0                2019      Russell Crowe          Gladiator
1                2019  Leonardo DiCaprio          Inception
2                2019  Leonardo DiCaprio          Inception
3                2019       Kate Winslet            Titanic
4                2018          Tom Hanks       Forrest Gump
...               ...                ...                ...
1624             2001  Robert Downey Jr.  Avengers: Endgame
1625             2001       Kate Winslet            Titanic
1626             2018          Brad Pitt         Fight Club
1627             2019     Cillian Murphy        Oppenheimer
1628             2011       Kate Winslet            Titanic

[1629 rows x 3 columns]

In [518]:
cricket[['Team1','Team2','WinningTeam']]

           Team1         Team2  WinningTeam
0       Pakistan   West Indies     Pakistan
1     Bangladesh      Pakistan   Bangladesh
2    West Indies      Pakistan  West Indies
3       Pakistan     Sri Lanka     Pakistan
4    New Zealand     Sri Lanka    Sri Lanka
..           ...           ...          ...
113      England   New Zealand  New Zealand
114    Australia  South Africa    Australia
115  New Zealand    Bangladesh  New Zealand
116    Australia      Pakistan    Australia
117  New Zealand    Bangladesh   Bangladesh

[118 rows x 3 columns]

In [519]:
type(cricket[['Team1','Team2','WinningTeam']])

pandas.core.frame.DataFrame

### Selecting rows from a DataFrame

- **iloc** - searches using index positions
- **loc** - searches using index labels

In [520]:
# single row
students.iloc[1]

iq         90
percent    70
lpa         7
Name: Labib, dtype: int64

In [521]:
type(students.iloc[1])

pandas.core.series.Series

In [522]:
# multiple row
students.iloc[:4]

         iq  percent  lpa
name
Sony    100       80   10
Labib    90       70    7
Hasan   120      100   14
Rahman   80       50    2

In [523]:
type(students.iloc[:4])

pandas.core.frame.DataFrame

In [524]:
students.iloc[:5:2]

        iq  percent  lpa
name
Sony   100       80   10
Hasan  120      100   14
Zaman    0        0    0

In [525]:
# fancy indexing
students.iloc[[0,2,4,5]]

        iq  percent  lpa
name
Sony   100       80   10
Hasan  120      100   14
Zaman    0        0    0
Karim    0        0    0

In [526]:
# loc
students

         iq  percent  lpa
name
Sony    100       80   10
Labib    90       70    7
Hasan   120      100   14
Rahman   80       50    2
Zaman     0        0    0
Karim     0        0    0

In [527]:
students.loc['Sony']

iq         100
percent     80
lpa         10
Name: Sony, dtype: int64

In [528]:
students.loc['Labib':'Karim':2]

        iq  percent  lpa
name
Labib   90       70    7
Rahman  80       50    2
Karim    0        0    0

In [529]:
students.loc[['Sony','Hasan','Zaman']]

        iq  percent  lpa
name
Sony   100       80   10
Hasan  120      100   14
Zaman    0        0    0

In [530]:
students.iloc[[0,3,4]]

         iq  percent  lpa
name
Sony    100       80   10
Rahman   80       50    2
Zaman     0        0    0

### Selecting both rows and cols

In [531]:
students.iloc[1:3,1:3]

       percent  lpa
name
Labib       70    7
Hasan      100   14

In [532]:
students.loc['Hasan':'Zaman',:'percent']

         iq  percent
name
Hasan   120      100
Rahman   80       50
Zaman     0        0

### Filtering a DataFrame

In [533]:
cricket.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1304113,Melbourne,2022-05-19,2022,67,Pakistan,West Indies,Eden Gardens,Pakistan,bat,N,Pakistan,Wickets,8.0,NaN,Mohammad Rizwan,"Babar Azam, Shaheen Afridi, Mohammad Rizwan","Kane Williamson, Trent Boult, Devon Conway",Richard Kettleborough,Chris Gaffaney
1,1304107,Melbourne,2022-05-14,2022,61,Bangladesh,Pakistan,Sher-e-Bangla National Stadium,Bangladesh,bat,N,Bangladesh,Runs,54.0,NaN,Shakib Al Hasan,"Babar Azam, Shaheen Afridi, Mohammad Rizwan","Shakib Al Hasan, Tamim Iqbal, Mustafizur Rahman",Aleem Dar,Paul Reiffel

In [534]:
# find all the final winners
mask = cricket['MatchNumber'] == 'Final'
new_df = cricket[mask]
new_df[['Season','WinningTeam']]

Empty DataFrame
Columns: [Season, WinningTeam]
Index: []

In [535]:
# in one line
cricket[cricket['MatchNumber'] == 'Final'][['Season','WinningTeam']]

Empty DataFrame
Columns: [Season, WinningTeam]
Index: []

In [536]:
# how many super over finishes have occured
cricket[cricket['SuperOver'] == 'Y'].shape[0]

1

In [537]:
# how many matches has Australia won in Sydney
cricket[(cricket['City'] == 'Sydney') & (cricket['WinningTeam'] == 'Australia')].shape[0]

5

In [538]:
# toss winner is match winner in percentage
(cricket[cricket['TossWinner'] == cricket['WinningTeam']].shape[0]/cricket.shape[0])*100

88.98305084745762

In [539]:
# movies with rating higher than 8 and votes>10000
movies[(movies['imdb_rating'] > 8.0) & (movies['imdb_votes'] > 10000)].shape[0]

43

In [540]:
# Action movies with rating higher than 7.5
# mask1 = movies['genres'].str.split('|').apply(lambda x:'Action' in x)
mask1 = movies['genres'].str.contains('Action')
mask2 = movies['imdb_rating'] > 7.5

movies[mask1 & mask2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Gladiator,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Russell Crowe,4 wins,11 January 2019 (USA)
41,Avengers: Endgame,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,NaN,Robert Downey Jr.,NaN,19 July 2019 (India)
84,Forrest Gump,tt7180544,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mukkabaaz,The Brawler,Mukkabaaz,0,2017,154,Action|Drama|Sport,8.1,5434,A boxer (Shravan) belonging to upper cast tra...,A boxer struggles to make his mark in the boxi...,NaN,Tom Hanks,3 wins & 6 nominations,12 January 2018 (USA)
106,Fight Club,tt7098658,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raazi,Raazi,Raazi,0,2018,138,Action|Drama|Thriller,7.8,20289,Hidayat Khan is the son of an Indian freedom f...,A Kashmiri woman agrees to marry a Pakistani a...,An incredible true story,Brad Pitt,21 wins & 26 nominations,11 May 2018 (USA)
110,Inception,tt6826438,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Parmanu:_The_Sto...,Parmanu: The Story of Pokhran,Parmanu: The Story of Pokhran,0,2018,129,Action|Drama|History,7.7,18292,Captain Ashwat Raina's efforts to turn India i...,Ashwat Raina and his teammates arrive in Pokhr...,1998| India: one secret operation| six Indians...,Leonardo DiCaprio,NaN,25 May 2018 (USA)
112,Oppenheimer,tt6129302,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bhavesh_Joshi_Su...,Bhavesh Joshi Superhero,Bhavesh Joshi Superhero,0,2018,154,Action|Drama,7.6,4928,Bhavesh Joshi Superhero is an action film abou...,The origin story of Bhavesh Joshi an Indian s...,This year| justice will have a new name.,Cillian Murphy,2 nominations,1 June 2018 (USA)
169,Avengers: Endgame,tt6299040,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Ghazi_Attack...,The Ghazi Attack,The Ghazi Attack,0,2017,116,Action|Thriller|War,7.6,10332,In 1971 amid rising tensions between India an...,A Pakistani submarine Ghazi plans to secretly...,The war you did not know about,Robert Downey Jr.,1 win & 7 nominations,17 February 2017 (USA)
219,The Dark Knight,tt6080746,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raagdesh,Raag Desh,Raag Desh,0,2017,135,Action|Drama|History,8.3,341,A period film based on the historic 1945 India...,A period film based on the historic 1945 India...,NaN,Christian Bale,NaN,28 July 2017 (India)
258,Inception,tt5310090,https://upload.wikimedia.org/wikipedia/en/f/fe...,https://en.wikipedia.org/wiki/Saala_Khadoos,Saala Khadoos,Saala Khadoos,0,2016,109,Action|Drama|Sport,7.6,10507,An under-fire boxing coach Prabhu is transfer...,The story of a former boxer who quits boxing f...,NaN,Leonardo DiCaprio,9 wins & 2 nominations,29 January 2016 (USA)
280,Gladiator,tt5600714,NaN,https://en.wikipedia.org/wiki/Laal_Rang,Laal Rang,Laal Rang,0,2016,147,Action|Crime|Drama,8.0,3741,The friendship of two men is tested when thing...,The friendship of two men is tested when thing...,Every job good or bad| must be done with honesty.,Russell Crowe,NaN,22 April 2016 (India)
297,Deadpool,tt4434004,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Udta_Punjab,Udta Punjab,Udta Punjab,0,2016,148,Action|Crime|Drama,7.8,23995,What on earth can a rock star a migrant labor...,A story that revolves around drug abuse in the...,NaN,Ryan Reynolds,11 wins & 19 nominations,17 June 2016 (USA)
354,Avengers: Endgame,tt5074352,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dangal_(film),Dangal,Dangal,0,2016,161,Action|Biography|Drama,8.4,131338,Biopic of Mahavir Singh Phogat who taught wre...,Former wrestler Mahavir Singh Phogat and his t...,You think our girls are any lesser than boys?,Robert Downey Jr.,23 wins & 4 nominations,21 December 2016 (USA)
362,John Wick,tt3863552,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bajrangi_Bhaijaan,Bajrangi Bhaijaan,Bajrangi Bhaijaan,0,2015,163,Action|Comedy|Drama,8.0,65877,A little mute girl from a Pakistani village ge...,An Indian man with a magnanimous heart takes a...,NaN,Keanu Reeves,25 wins & 13 nominations,17 July 2015 (USA)
365,Fight Club,tt3848892,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Baby_(2015_Hindi...,Baby,Baby,0,2015,159,Action|Thriller,8.0,49426,The country is perpetually under threat from t...,An elite counter-intelligence unit learns of a...,History Is Made By Those Who Give A Damn!,Brad Pitt,1 win,23 January 2015 (India)
393,The Dark Knight,tt3447364,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Detective_Byomke...,Detective Byomkesh Bakshy!,Detective Byomkesh Bakshy!,0,2015,139,Action|Mystery|Thriller,7.6,14674,CALCUTTA 1943 A WAR - A MYSTERY - and A DETECT...,While investigating the disappearance of a che...,Expect The Unexpected,Christian Bale,NaN,3 April 2015 (USA)
449,John Wick,tt3019620,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Titli_(2014_film),Titli,Titli,0,2014,116,Action|Drama|Thriller,7.6,3677,In the badlands of Delhi's dystopic underbelly...,A Hindi feature film set in the lower depths o...,Daring| Desireable| Dangerous,Keanu Reeves,4 wins & 5 nominations,20 June 2014 (USA)
536,Avatar,tt3390572,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Haider_(film),Haider,Haider,0,2014,160,Action|Crime|Drama,8.1,46912,Vishal Bhardwaj's adaptation of William Shakes...,A young man returns to Kashmir after his fathe...,NaN,Sam Worthington,28 wins & 24 nominations,2 October 2014 (USA)
589,Avengers: Endgame,tt2199711,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Vishwaroop_(Hind...,Vishwaroopam,Vishwaroopam,0,2013,148,Action|Thriller,8.2,38016,Vishwanathan a Kathak dance teacher in New Yo...,When a classical dancer's suspecting wife sets...,NaN,Robert Downey Jr.,5 wins & 11 nominations,25 January 2013 (India)
625,Deadpool,tt2855648,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Madras_Cafe,Madras Cafe,Madras Cafe,0,2013,130,Action|Drama|Thriller,7.7,21393,An Indian Intelligence agent (portrayed by Joh...,An Indian intelligence agent journeys to a war...,NaN,Ryan Reynolds,10 wins & 10 nominations,23 August 2013 (India)
668,Avengers: Endgame,tt1620933,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Paan_Singh_Tomar...,Paan Singh Tomar,Paan Singh Tomar,0,2012,135,Action|Biography|Crime,8.2,29994,Paan Singh Tomar is a Hindi-language film bas...,The story of Paan Singh Tomar an Indian athle...,NaN,Robert Downey Jr.,10 wins & 11 nominations,2 March 2012 (USA)
693,John Wick,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseypur,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Keanu Reeves,12 wins & 43 nominations,2 August 2012 (Singapore)
694,Titanic,tt1954470,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangs_of_Wasseyp...,Gangs of Wasseypur,Gangs of Wasseypur,0,2012,321,Action|Comedy|Crime,8.2,71636,Shahid Khan is exiled after impersonating the ...,A clash between Sultan and Shahid Khan leads t...,NaN,Kate Winslet,12 wins & 43 nominations,2 August 2012 (Singapore)
982,Joker,tt0449994,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jodhaa_Akbar,Jodhaa Akbar,Jodhaa Akbar,0,2008,213,Action|Drama|History,7.6,27541,Jodhaa Akbar is a sixteenth century love story...,A sixteenth century love story about a marriag...,NaN,Joaquin Phoenix,32 wins & 21 nominations,15 February 2008 (USA)
1039,Forrest Gump,tt0983990,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/1971_(2007_film),1971,1971,0,2007,160,Action|Drama|War,7.9,1121,Based on true facts the film revolves around ...,Based on true facts the film revolves around ...,Honor the heroes.......,Tom Hanks,1 win,9 March 2007 (India)
1058,The Dark Knight,tt0400234,https://upload.wikimedia.org/wikipedia/en/5/58...,https://en.wikipedia.org/wiki/Black_Friday_(20...,Black Friday,Black Friday,0,2004,143,Action|Crime|Drama,8.5,16761,A dramatic presentation of the bomb blasts tha...,Black Friday is a film about the investigation...,The story of the Bombay bomb blasts,Christian Bale,3 nominations,9 February 2007 (India)
1188,Joker,tt0488414,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Omkara_(2006_film),Omkara,Omkara,0,2006,155,Action|Crime|Drama,8.1,17594,Advocate Raghunath Mishra has arranged the mar...,A politically-minded enforcer's misguided trus...,NaN,Joaquin Phoenix,19 wins & 20 nominations,28 July 2006 (USA)
1293,Avengers: Endgame,tt0432047,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sarkar_(2005_film),Sarkar,Sarkar,0,2005,124,Action|Crime|Drama,7.6,14694,Meet Subhash Nagre - a wealthy and influential...,The authority of a man who runs a parallel go...,'There are no Rights and Wrongs. Only Power' -...,Robert Downey Jr.,2 wins & 10 nominations,1 July 2005 (India)
1294,Joker,tt0477857,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sehar,Sehar,Sehar,0,2005,125,Action|Crime|Drama,7.8,1861,At the tender age of 8 Ajay Kumar is traumatiz...,Ajay Kumar the newly appointed honest SSP of ...,NaN,Joaquin Phoenix,NaN,29 July 2005 (India)
1361,Titanic,tt0323013,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lakshya_(film),Lakshya,Lakshya,0,2004,186,Action|Drama|Romance,7.9,18777,Karan is a lazy good-for-nothing who lives on ...,An aimless jobless irresponsible grown man j...,It took him 24 years and 18000 feet to find hi...,Kate Winslet,4 wins & 10 nominations,18 June 2004 (USA)
1432,Joker,tt0373856,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gangaajal,Gangaajal,Gangaajal,0,2003,157,Action|Crime|Drama,7.8,14295,An SP Amit Kumar who is given charge of Tezpur...,An IPS officer motivates and leads a dysfuncti...,NaN,Joaquin Phoenix,4 wins & 29 nominations,29 August 2003 (India)
1495,Oppenheimer,tt0296574,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Company_(film),Company,Company,0,2002,155,Action|Crime|Drama,8.0,13474,Mallik is a henchman of Aslam Bhai a Mumbai u...,A small-time gangster named Chandu teams up wi...,A law & order enterprise,Cillian Murphy,16 wins & 9 nominations,15 April 2002 (India)
1554,Avengers: Endgame,tt0319736,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Legend_of_Bh...,The Legend of Bhagat Singh,The Legend of Bhagat Singh,0,2002,155,Action|Biography|Drama,8.1,13455,Bhagat was born in British India during the ye...,The story of a young revolutionary who raised ...,NaN,Robert Downey Jr.,11 wins & 5 nominations,7 June 2002 (India)
1607,Top Gun: Maverick,tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Tom Cruise,2 nominations,7 September 2001 (India)

In [541]:
# write a function that can return the track record of 2 teams against each other
cricket[((cricket['Team1']=='Australia') & (cricket['Team2']=='England') )|((cricket['Team1']=='England') & (cricket['Team2']=='Australia') )]['Team1']

25    Australia
54    Australia
57    Australia
97    Australia
Name: Team1, dtype: object

### Adding new cols

In [542]:
# add new column Certified
movies['Certified'] = True
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Certified
0,Gladiator,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Russell Crowe,4 wins,11 January 2019 (USA),True
1,Inception,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Leonardo DiCaprio,NaN,11 January 2019 (India),True
2,Inception,tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Leonardo DiCaprio,NaN,11 January 2019 (USA),True
3,Titanic,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Kate Winslet,NaN,18 January 2019 (USA),True
4,Forrest Gump,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Tom Hanks,17 wins & 1 nomination,11 January 2019 (India),True

In [543]:
# Remove rows that contain missing values
movies.dropna(inplace=True)

In [544]:
# Add a new column named 'prize_count', where the values are extracted from 'wins_nominations'
movies['prize_count'] = movies['wins_nominations'].str.split(' ').apply(lambda x: x[0])

movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Certified,prize_count
11,Oppenheimer,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Cillian Murphy,6 wins & 3 nominations,14 February 2019 (USA),True,6
34,Inception,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Leonardo DiCaprio,2 wins & 1 nomination,24 May 2019 (India),True,2
37,Top Gun: Maverick,tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Tom Cruise,1 win,28 June 2019 (USA),True,1
87,Avengers: Endgame,tt6774212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aiyaary,Aiyaary,Aiyaary,0,2018,157,Action|Thriller,5.2,3538,General Gurinder Singh comes with a proposal t...,After finding out about an illegal arms deal ...,The Ultimate Trickery,Robert Downey Jr.,1 nomination,16 February 2018 (USA),True,1
96,Gladiator,tt7363076,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raid_(2018_film),Raid,Raid,0,2018,122,Action|Crime|Drama,7.4,13159,Set in the 80s in Uttar Pradesh India Raid i...,A fearless income tax officer raids the mansio...,Heroes don't always come in uniform,Russell Crowe,2 wins & 3 nominations,16 March 2018 (India),True,2

In [545]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 298 entries, 11 to 1623
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           298 non-null    object
 1   imdb_id           298 non-null    object
 2   poster_path       298 non-null    object
 3   wiki_link         298 non-null    object
 4   title_y           298 non-null    object
 5   original_title    298 non-null    object
 6   is_adult          298 non-null    int64
 7   year_of_release   298 non-null    int64
 8   runtime           298 non-null    object
 9   genres            298 non-null    object
 10  imdb_rating       298 non-null    float64
 11  imdb_votes        298 non-null    int64
 12  story             298 non-null    object
 13  summary           298 non-null    object
 14  tagline           298 non-null    object
 15  actors            298 non-null    object
 16  wins_nominations  298 non-null    object
 17  release_date      298 non-null    object
 18  Certified         298 non-null    bool
 19  prize_count       298 non-null    object
dtypes: bool(1), float64(1), int64(3), object(15)
memory usage: 46.9+ KB

### Important DataFrame Functions

In [546]:
# astype() is used to change the data type of a given column
cricket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               118 non-null    int64
 1   City             118 non-null    object
 2   Date             118 non-null    object
 3   Season           118 non-null    object
 4   MatchNumber      118 non-null    object
 5   Team1            118 non-null    object
 6   Team2            118 non-null    object
 7   Venue            118 non-null    object
 8   TossWinner       118 non-null    object
 9   TossDecision     118 non-null    object
 10  SuperOver        117 non-null    object
 11  WinningTeam      118 non-null    object
 12  WonBy            118 non-null    object
 13  Margin           116 non-null    float64
 14  method           3 non-null      object
 15  Player_of_Match  118 non-null    object
 16  Team1Players     118 non-null    object
 17  Team2Players     118 non-null    object
 18  Umpire1          118 non-null    object
 19  Umpire2          118 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 18.6+ KB

In [547]:
cricket['ID'] = cricket['ID'].astype('int32')

In [548]:
cricket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               118 non-null    int32
 1   City             118 non-null    object
 2   Date             118 non-null    object
 3   Season           118 non-null    object
 4   MatchNumber      118 non-null    object
 5   Team1            118 non-null    object
 6   Team2            118 non-null    object
 7   Venue            118 non-null    object
 8   TossWinner       118 non-null    object
 9   TossDecision     118 non-null    object
 10  SuperOver        117 non-null    object
 11  WinningTeam      118 non-null    object
 12  WonBy            118 non-null    object
 13  Margin           116 non-null    float64
 14  method           3 non-null      object
 15  Player_of_Match  118 non-null    object
 16  Team1Players     118 non-null    object
 17  Team2Players     118 non-null    object
 18  Umpire1          118 non-null    object
 19  Umpire2          118 non-null    object
dtypes: float64(1), int32(1), object(18)
memory usage: 18.1+ KB

In [549]:
# Convert 'toss_decision' and 'super_over' columns into category data type
cricket['TossDecision'] = cricket['TossDecision'].astype('category')
cricket['SuperOver'] = cricket['SuperOver'] .astype('category')

In [550]:
cricket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               118 non-null    int32
 1   City             118 non-null    object
 2   Date             118 non-null    object
 3   Season           118 non-null    object
 4   MatchNumber      118 non-null    object
 5   Team1            118 non-null    object
 6   Team2            118 non-null    object
 7   Venue            118 non-null    object
 8   TossWinner       118 non-null    object
 9   TossDecision     118 non-null    category
 10  SuperOver        117 non-null    category
 11  WinningTeam      118 non-null    object
 12  WonBy            118 non-null    object
 13  Margin           116 non-null    float64
 14  method           3 non-null      object
 15  Player_of_Match  118 non-null    object
 16  Team1Players     118 non-null    object
 17  Team2Players     118 non-null    object
 18  Umpire1          118 non-null    object
 19  Umpire2          118 non-null    object
dtypes: category(2), float64(1), int32(1), object(16)
memory usage: 16.7+ KB

In [551]:
cricket['City'].value_counts()

City
Mumbai        15
Sydney        15
Adelaide      15
Manchester    13
Dhaka         12
Kolkata       11
London        11
Ahmedabad     10
Melbourne      8
Lahore         8
Name: count, dtype: int64

In [552]:
# how many matches each team has played
pd.concat([cricket['Team1'], cricket['Team2']]).value_counts()

Pakistan        28
New Zealand     27
India           27
Bangladesh      24
Sri Lanka       24
South Africa    23
Afghanistan     22
West Indies     22
Australia       20
England         19
Name: count, dtype: int64

In [553]:
# sort_values -> ascending -> na_position -> inplace -> multiple cols
students.sort_values(by=['iq', 'percent'], ascending=[True, False], na_position='first', inplace=True)
students

         iq  percent  lpa
name
Zaman     0        0    0
Karim     0        0    0
Rahman   80       50    2
Labib    90       70    7
Sony    100       80   10
Hasan   120      100   14